name: Nix + Open Policy Agent

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    environment: build
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Check Nixpkgs input
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Set up Nix environment
        run: |
          nix develop ".#ci" --command direnv allow
          eval "$(nix develop ".#ci" --command direnv export bash)"
          echo "$PATH" >> $GITHUB_PATH

      - name: Nix checks
        run: |
          nix flake check --all-systems
