name: Nix + Open Policy Agent

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-and-build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    environment: build
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Nix checks
        run: |
          nix flake check --all-systems

      - name: Nix build
        run: |
          nix build .#check-flake
          nix build .#flake-checker
          nix build .#rbac-eval
          nix build .#tfstate-eval
